name: Sync

on:
  push:
    paths:
      - ".github/workflows/sync.yml"
  schedule:
    - cron: "0 9 * * *"

jobs:
  # sync-to-this-repo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false
  #     - name: repo-sync
  #       uses: repo-sync/github-sync@v2
  #       with:
  #         source_repo: "https://gitlab.com/letr.rod/mmmerge.git"
  #         source_branch: "Rodril_nightly_build"
  #         destination_branch: "sync"
  #         github_token: ${{ secrets.GITHUB_TOKEN }}


  sync-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://gitlab.com/letr.rod/mmmerge.git"
          source_branch: "Rodril_nightly_build"
          destination_repo: "git@github.com:might-and-magic/mmmerge-backup.git"
          destination_branch: "main"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
